---

# Playbook to setup bastion instances
# We want to run a private docker registry among other things.

- name: Setup Bastion nodes
  hosts: '{{ bastion_hosts | default("bastions") }}'
  gather_facts: yes
  become: true
  roles:
    - epel-repo
    - base_config
    - docker_ce

