---

# Playbook to setup bastion instances
# We want to run a private docker registry among other things.

- name: Setup Bastion nodes
  hosts: bastions
  gather_facts: yes
  become: true
  roles:
    - epel-repo
    - base_config
    - docker_ce


# TODO: To inssall wangsha's version of docker registry
#   ansible-galaxy install wangsha.docker-registry -p ./roles
# Then use role - however, may implement own
#    - wangsha.docker-registry
