---

# Playbook to setup manager instances

- name: Setup manager nodes
  hosts: '{{ target | default("managers") }}'
  #gather_facts: no
  become: true
  roles:
    - epel-repo
    - base_config
    - docker_ce
