---

# Playbook to setup worker instances

- name: Setup worker nodes
  hosts: '{{ worker_hosts | default("workers") }}'
  #gather_facts: no
  become: true
  roles:
    - epel-repo
    - base_config
    - docker_ce
