---

- name: Schedule ansible-pull
  cron:
    name: "Check for config changes"
    cron_file: /etc/crontab
    user: "centos"
    minute: "*"
    hour: "*"
    job: "/usr/bin/ansible-pull -U {{ DEPLOYMENT_REPO }} --full -o -s 20 -e target=self {{ DEPLOYMENT_PLAY }}"

