---

- name: "Installing lynx"
  yum:
    name: lynx
    state: present

- name: Schedule ansible-pull
  cron:
    name: "Check for config changes"
    cron_file: /etc/crontab
    user: "centos"
    minute: "*"
    hour: "*"
    job: "/usr/bin/ansible-pull -U {{ DEPLOYMENT_REPO }} -e target=localhost {{ DEPLOYMENT_PLAY }}"
    #    "/usr/bin/ansible-pull -U https://github.com/JohanWindRiver/ZGVwbG95MTAx.git --force -e targets=localhost services.yml"

