---

# Variables specific to the setup of an etcd cluster
# To generate a discovery token use:
#  curl -s https://discovery.etcd.io/new?size={{ TOKEN_COUNT }}

DISCOVERY_TOKEN: "https://discovery.etcd.io/a83d248f63f1abf361ed7f4fbb54b391"
TOKEN_COUNT: "1"

etcd_version: 'latest'
etcd_image: "quay.io/coreos/etcd:{{etcd_version}}"
etcd_peers_group: etcd_servers

etcd_client_port: 2379
etcd_url_scheme: http
etcd_peer_port: 2380
etcd_interface: eth0
etcd_client_interface: "{{ etcd_interface }}"
etcd_peer_interface: "{{ etcd_interface }}"

etcd_name: "{{ hostvars[inventory_hostname]['ansible_' + etcd_peer_interface]['ipv4']['address'] }}"
etcd_advertise_client_urls: "{{ etcd_client_url_scheme }}://{{ hostvars[inventory_hostname]['ansible_' + etcd_client_interface]['ipv4']['address'] }}:{{ etcd_client_port }}"
#etcd_listen_client_urls: "{{ etcd_client_url_scheme }}://{{ hostvars[inventory_hostname]['ansible_' + etcd_client_interface]['ipv4']['address'] }}:{{ etcd_client_port }}"
etcd_listen_client_urls: "{{ etcd_client_url_scheme }}://0.0.0.0:{{ etcd_client_port }}"
etcd_client_url_scheme: "{{ etcd_url_scheme }}"
etcd_peer_url_scheme: "{{ etcd_url_scheme }}"
etcd_initial_advertise_peer_urls: "{{ etcd_peer_url_scheme }}://{{ hostvars[inventory_hostname]['ansible_' + etcd_peer_interface]['ipv4']['address'] }}:{{ etcd_peer_port }}"
#etcd_listen_peer_urls: "{{ etcd_peer_url_scheme }}://{{ hostvars[inventory_hostname]['ansible_' + etcd_peer_interface]['ipv4']['address'] }}:{{ etcd_peer_port }}"
etcd_listen_peer_urls: "{{ etcd_peer_url_scheme }}://0.0.0.0:{{ etcd_peer_port }}"
etcd_initial_cluster_token: etcd-cluster-1

etcd_initial_cluster: "
        {%- if etcd_peers is defined -%}
            {% for host in etcd_peers %}{{ host }}={{ etcd_peer_url_scheme }}://{{ host }}:{{ etcd_peer_port }}{% if not loop.last %},{% endif %}{% endfor %}
        {%- else -%}
            {% for host in groups[etcd_peers_group] -%}{{ host }}={{ etcd_peer_url_scheme }}://{{ hostvars[host]['ansible_' + etcd_peer_interface]['ipv4']['address'] }}:{{ etcd_peer_port }}{% if not loop.last %},{% endif %}{% endfor %}
    {%- endif -%}
"

etcd_initial_cluster_state: "new"


